### ISSUE TITLE
Implement recommended community standards to the project

### ISSUE THREAD

**Issue by orama254** [akshaykhoje/my_linux_scripts#13]
Hello @akshaykhoje 

I was going though this project and noticed that there are some missing items based on the [Github Community Standards recommendations](https://github.com/akshaykhoje/my_linux_scripts/community) that would make the project contributor friendly, e.g. a code of conduct, an issue template and a pull request template.

Let me know if this is something you would like to implement on this project.

**Comment by akshaykhoje** [comment]
Thanks for the suggestions.

I would like to implement that in my project. However, in the context of Hacktoberfest, I don't think that could be considered a valid PR.

**Comment by orama254** [comment]
Nice to know, 

I've done these kinds of contributions before that have been valid PRs in the context of Hacktoberfest.

Moreover, right now I am doing contributions to participating projects to make them contributor friendly for Hacktoberfest and beyond.

**Comment by akshaykhoje** [comment]
Cool. 
Go ahead then.  I will merge them :)
