### ISSUE TITLE
".wgetrc" file NOT created by the script!

### ISSUE THREAD

**Issue by akshaykhoje** [akshaykhoje/my_linux_scripts#3]
So this has been an issue since the time of publicising the repository. The dotfile for wget proxy setup does not get created from commands within the script. However when same commands are run from outside the script and on the terminal they work perfectly fine.

Bottomline, UNABLE TO CREATE AND WRITE TO THE ".wgetrc" FILE IN THE HOME DIRECTORY

**Comment by akshaykhoje** [comment]
Bug resolved!

**Comment by akshaykhoje** [comment]
Bug fixed!

**Comment by mithil404** [comment]
#12  Added fix in the pull request.
