### ISSUE TITLE
How do i uninstall it?

### ISSUE THREAD

**Issue by TanmayPatil105** [akshaykhoje/my_linux_scripts#4]

**Comment by akshaykhoje** [comment]
It's pretty simple. 
I added the uninstallation script for the proxy setup. 

The script can be found at :
https://github.com/akshaykhoje/my_linux_scripts/blob/master/proxies/uninstall.sh 

Download the uninstall.sh script and execute the following command in your terminal -
sudo ./uninstall.sh

If you faced any issues while using it, feel free to open an issue about the same. 

Thanks for using it 😇
